version: '2'
services:
    etatcivil-mysql:
        container_name: etatcivil-mysql
        image: mysql:5.7.12
        # volumes:
        #     - ~/volumes/jhipster/etatcivil/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=etatcivil
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl
